version: '3.9'

services:
  cassandra:
    image: cassandra:3
    container_name: spark-cassandra
    ports:
      - 7001:7001
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=CASSANDRA_CLUSTER_1
  #################################################################
  zookeeper:
    container_name: spark-zookeeper
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    restart: always
  #################################################################
  kafka:
    container_name: spark-kafka
    hostname: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost # has to be not local if using multiple brokers
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
    restart: always
  #################################################################

networks:
  default:
    external: true
    name: airflow_default
