version: '3.9'

services:
  fastapi:
    image: my_fastapi_image:latest
    container_name: fastapi_uvicorn
    ports:
      - 8111:8111
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8111
    volumes:
      - .:/opt/spark-learning/fastapi
    restart: always

networks:
  default:
    external: true
    name: airflow_default
